# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{fbdoorman}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["This gem: David Pelaez", "MiniFB:Appoxy", "Dan Croak", "Mike Burns", "Jason Morrison", "Joe Ferris", "Eugene Bolshakov", "Nick Quaranto", "Josh Nichols", "Mike Breen", "Marcel G\303\266rner", "Bence Nagy", "Ben Mabey", "Eloy Duran", "Tim Pope", "Mihai Anca", "Mark Cornick", "Shay Arnett", "Jon Yurek", "Chad Pytel"]
  s.date = %q{2010-07-17}
  s.description = %q{Painless user registration and sign-in using Facebook single sign-on with JS. Typical email login still works too.}
  s.email = %q{pelaez89{at}gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    "CHANGELOG.md",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "app/controllers/clearance/confirmations_controller.rb",
     "app/controllers/clearance/facebook_controller.rb",
     "app/controllers/clearance/passwords_controller.rb",
     "app/controllers/clearance/sessions_controller.rb",
     "app/controllers/clearance/users_controller.rb",
     "app/models/clearance_mailer.rb",
     "app/views/clearance_mailer/change_password.html.erb",
     "app/views/clearance_mailer/confirmation.html.erb",
     "app/views/facebook/_fbjs.html.erb",
     "app/views/facebook/closed.html.erb",
     "app/views/passwords/edit.html.erb",
     "app/views/passwords/new.html.erb",
     "app/views/sessions/new.html.erb",
     "app/views/users/_form.html.erb",
     "app/views/users/new.html.erb",
     "generators/fbdoorman/USAGE",
     "generators/fbdoorman/fbdoorman_generator.rb",
     "generators/fbdoorman/lib/insert_commands.rb",
     "generators/fbdoorman/lib/rake_commands.rb",
     "generators/fbdoorman/templates/README",
     "generators/fbdoorman/templates/clearance.rb",
     "generators/fbdoorman/templates/facebook.yml",
     "generators/fbdoorman/templates/factories.rb",
     "generators/fbdoorman/templates/migrations/create_users.rb",
     "generators/fbdoorman/templates/migrations/update_users.rb",
     "generators/fbdoorman/templates/user.rb",
     "lib/clearance/authentication.rb",
     "lib/clearance/configuration.rb",
     "lib/clearance/extensions/errors.rb",
     "lib/clearance/extensions/rescue.rb",
     "lib/clearance/routes.rb",
     "lib/clearance/user.rb",
     "lib/facebook_helpers.rb",
     "lib/fbdoorman.rb",
     "lib/mini_fb.rb",
     "rails/init.rb"
  ]
  s.homepage = %q{http://github.com/davidpelaez/minifb-clearance}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Rails authentication with facebook single sign-on OR email & password.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

